global:
  scrape_interval: 5s  # Adjust as needed
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'eismoinfo_app'
    metrics_path: '/lt/prometheus/metrics'
    static_configs:
      - targets: ['eismoinfo-app:8000']

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'  # Use the service name defined in docker-compose.yml
  
    